### ISSUE TITLE
Setting DOTNET_HOST_PATH is not a good move :)

### ISSUE THREAD

**Issue by dsyme** [ionide/proj-info#123]
ProjInfo sets DOTNET_HOST_PATH to an invalid value (the name of the currently executing program) when being run inside a .NET tool (e.g. `fsdocs.exe` rather than `dotnet.exe`) here https://github.com/ionide/proj-info/blob/6a6bdf3d34cded3dee6d3bf600e3fd5dbcf30030/src/Ionide.ProjInfo/Library.fs#L168

This is because the default logic for `dotnetPath` assumes the current process is `dotnet.exe` but for a tool host like `fsdocs.exe` it isn't run by `dotnet.exe`, e.g. https://github.com/ionide/proj-info/blob/6a6bdf3d34cded3dee6d3bf600e3fd5dbcf30030/src/Ionide.ProjInfo/Utils.fs#L39

In any case, the setting of `DOTNET_HOST_PATH` should be strongly protected by a try/finally?  If used at all?

(Setting `DOTNET_HOST_PATH` to an invalid value confuses the heck out of FSharp.Compiler.Service.dll )

**Comment by baronfel** [comment]
I think `DOTNET_HOST_PATH` was required for some msbuild targets/props/shenanigans, so we should require it in some way, but I agree with you that the last-chance fallback of the app name isn't suitable for cases where the caller is in an `AppHost` and not the `dotnet` host.  I think we can remove that last-chance and raise an exception in the init function if that's the case.  That will require callers to set at least one of the valid detection variables, though, which ideally would be represented as an input to the function somehow...

**Comment by baronfel** [comment]
One hurdle here is that the .NET SDK doesn't forward any of the environment variables we look for on to [local](https://github.com/dotnet/sdk/blob/main/src/Cli/dotnet/CommandFactory/CommandResolution/LocalToolsCommandResolver.cs#L100-L102) or [global](https://github.com/dotnet/sdk/blob/main/src/Cli/dotnet/CommandFactory/CommandResolution/DotnetToolsCommandResolver.cs#L45-L47) tools, like it does for [other commands](https://github.dev/dotnet/sdk).  It might be good to advocate for that feature, because as it stands, tools have no consistent way to detect the dotnet installation that's running them.

**Comment by baronfel** [comment]
Talking with some of the SDK team, the DOTNET_ROOT variable is only set if the install location isn't one of the well-known ones. So we should do probing if there's no DOTNET_ROOT.

**Comment by baronfel** [comment]
The final algorithm should look something like:
* DOTNET_HOST_PATH
* DOTNET_ROOT/DOTNET_ROOT(x86)
* probe PATH
* probe default install locations per-OS
* fail hard if none found

**Comment by baronfel** [comment]
@dsyme this was released in 0.55.1

**Comment by baronfel** [comment]
@dsyme ok, 0.55.2 has a more sane strategy that doesn't touch DOTNET_HOST_PATH
